"""AI-SOC Alert Prompt Builder

Builds structured LLM prompts for single-alert analysis.
Designed to give the LLM rich context for accurate threat assessment.
"""

from typing import Optional


class AlertPromptBuilder:
    """Builds structured prompts for alert analysis."""

    def build(self, alert: dict) -> str:
        """Build a complete prompt from an alert dictionary."""
        prompt = self._build_system_context()
        prompt += self._build_alert_context(alert)
        prompt += self._build_task_instruction()
        return prompt

    def _build_system_context(self) -> str:
        return """You are a Senior SOC Analyst working in an enterprise Security Operations Center.
You are analyzing a security alert generated by the AI-SOC detection platform.

Your task is to provide an accurate, concise analysis based ONLY on the information provided.
Do NOT invent facts, do NOT assume malware families, do NOT speculate about attacker identity.

---
"""  # noqa: W291

    def _build_alert_context(self, alert: dict) -> str:
        """Build the structured alert context section."""
        lines = []
        lines.append("## ALERT DETAILS")
        lines.append("")

        fields = [
            ("Alert ID", alert.get("id", alert.get("alert_id", "Unknown"))),
            ("Alert Name", alert.get("rule_name", alert.get("rule", "Unknown"))),
            ("Severity", alert.get("severity", "Unknown")),
            ("Status", alert.get("status", "Unknown")),
            ("Timestamp", alert.get("timestamp", "Unknown")),
            ("Risk Score", str(alert.get("risk_score", "N/A"))),
            ("Confidence", str(alert.get("confidence", "N/A"))),
        ]
        for label, value in fields:
            lines.append(f"- **{label}:** {value}")

        lines.append("")
        lines.append("## SOURCE CONTEXT")
        lines.append("")

        source_fields = [
            ("Host", alert.get("host", alert.get("computer", "Unknown"))),
            ("User", alert.get("user", "Unknown")),
            ("Process", alert.get("process_name", alert.get("image", "Unknown"))),
            ("Command Line", alert.get("command_line", alert.get("command", "N/A"))),
        ]
        for label, value in source_fields:
            lines.append(f"- **{label}:** {value}")

        mitre_technique = alert.get("mitre_technique") or (
            alert.get("mitre", [None])[0] if alert.get("mitre") else None
        )
        mitre_tactic = alert.get("mitre_tactic", None)

        if mitre_technique or mitre_tactic:
            lines.append("")
            lines.append("## MITRE ATT&CK MAPPING")
            lines.append("")
            if mitre_tactic:
                lines.append(f"- **Tactic:** {mitre_tactic}")
            if mitre_technique:
                lines.append(f"- **Technique:** {mitre_technique}")

        description = alert.get("description", alert.get("reason", ""))
        if description:
            lines.append("")
            lines.append("## ALERT DESCRIPTION")
            lines.append("")
            lines.append(description)

        lines.append("")
        return "\n".join(lines)

    def _build_task_instruction(self) -> str:
        return """## YOUR ANALYSIS

Analyze the alert above and provide your assessment in the following JSON format.
Return ONLY valid JSON. No markdown, no explanations outside the JSON.

{
    "summary": "A concise 2-3 sentence summary of what happened and why it matters.",
    "confidence": 94,
    "severity": "High",
    "mitre": "T1059.001",
    "reasoning": "A detailed explanation of your reasoning, including which indicators triggered the alert and what the activity suggests.",
    "recommended_actions": [
        "Immediate action step 1",
        "Follow-up investigation step 2",
        "Long-term remediation step 3"
    ],
    "false_positive_probability": "Low"
}

Rules:
- summary: 2-3 sentences, plain text
- confidence: integer 0-100
- severity: one of "Critical", "High", "Medium", "Low", "Info"
- mitre: MITRE ATT&CK technique ID if applicable, or an empty string ""
- reasoning: detailed paragraph explaining the analysis
- recommended_actions: array of 2-5 action strings
- false_positive_probability: one of "Very Low", "Low", "Medium", "High", "Very High"
"""
